# preload = /home/alexandr/Pictures/wallpapers/photo_2026-02-03_00-54-58.jpg
# wallpaper = HDMI-A-1,/home/alexandr/Pictures/wallpapers/photo_2026-02-03_00-54-58.jpg

# wallpaper {
#     monitor = 
#     path = ~/Pictures/wallpapers/RDT_20260223_1622547581249994796147557.jpg
#     fit_mode = cover
# }

# ~/.config/hypr/hyprpaper.conf

preload = ~/Pictures/wallpapers/main.jpg
preload = ~/Pictures/wallpapers/second.jpg
preload = ~/Pictures/wallpapers/arch.jpg

wallpaper {
    monitor = DP-1
    path = ~/Pictures/wallpapers/main.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/wallpapers/arch.jpg
    fit_mode = cover
}
